---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
  name: pwpush-data-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /your/path/here
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem
...
