apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
    {{- range $k, $v := .Values.deployment.labels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
