base: &base
  adapter: sqlite3
  timeout: 5000
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>

development:
  database: db/development.sqlite3
  <<: *base

test:
  database: db/test.sqlite3
  <<: *base

private:
  database: db/private.sqlite3
  <<: *base

production:
  database: db/production.sqlite3
  <<: *base
